name: React Deploy Pipeline

on:
  workflow_run:
    workflows: ["React Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      #### 1. Dowload build artifact ####
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build-${{ github.run_number }}
          path: build/

      - name: Verify downloaded artifact
        run: |
          echo "Build artifact 'react-build-${{ github.run_number }}' downloaded successfully."
          echo "Contents of the build directory:"
          ls -la build/

      #### 2. Deploy to GitHub Pages ####
      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build

      #### 3. Deployment success message ####
      - name: Deployment status message
        run: |
          if [ "${{ steps.deploy.outcome }}" = "success" ]; then
            echo "Deployment succeeded."
          else
            echo "Deployment failed. Please check the logs for details."
            exit 1
          fi
